---
- name: Install packages
  hosts: all

  tasks:
    - name: Install packages
      become: true
      ansible.builtin.package:
        name:
          - git
          - git-lfs
          - bat
          - tree
          - neovim
        state: latest

- name: Install Ollama
  hosts: gpu

  tasks:
    - name: Install Ollama
      become: true
      ansible.builtin.shell:
        cmd: curl -fsSL https://ollama.com/install.sh | sh

    - name: Install Claude Code
      become: true
      ansible.builtin.shell:
        cmd: curl -fsSL https://claude.ai/install.sh | bash

